name: fk_booster
description: "A Flutter project that helps you to boost your development"
version: 0.0.2
repository: https://github.com/CaioCoelhoChaves/fk_booster

environment:
  sdk: ^3.10.4

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.2.4
  mocktail: ^1.0.4
  signals: ^6.0.2
  sqflite: ^2.4.2
  very_good_analysis: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
